STRIPE_SECRET_KEY = "sk_test_51SNdNlC20flbf1hAK2LiwwJyfC4LdDiOdd8qMcM6xd3cWqENcvkIaUkiHrb0I0wLoNHW0KpGFDSU75TVojacWAMo00eyGw6dfh"
STRIPE_PUBLISHABLE_KEY = "pk_test_51SNdNlC20flbf1hAp0FoQLTppgIGuXzGEIWavR41ib3qHhlks5dpuoNV7gMnR5haNees5MPawAlhDKEyWHGWfI4B00ZGgwZmxi"
